name: 'Qualification of userprog phase'

on:
  push:
    branches:
        - userprog
  pull_request:
    branches:
      - userprog

jobs:
  userprog:
    name: 'Phase: User Programs'
    runs-on: 'ubuntu-latest'
    env:
      phase: 'userprog'
    steps:
      - name: 'Cloning repository'
        uses: 'actions/checkout@v2'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install qemu
          sudo ln -s /usr/bin/qemu-system-i386 /usr/bin/qemu
      - name: Pintos Checker
        id: phase
        uses: gbenm/pintos-checker@v1
        with:
            phase: '${{ env.phase }}'
            root: "."
            utils_path: "utils"
            make: "make clean && make && make grade"
      - name: 'Show results'
        uses: './.github/pintos-results'
        with:
          results: "${{ steps.phase.outputs.results }}"
          phase: "${{ env.phase }}"